baseURL = "/"
languageCode = "en-us"
title = "josh's tech journey"
theme = "cactus"

publishDir = "public"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Now"
url = "/now"
weight = 4

[params]

colortheme = "dark"
description = "Hi, I'm Josh. Thanks for visiting, and feel free to check out the rest of my website! :)"

[[params.social]]
name = "github"
link = "https://github.com/joshtenorio"